In [4]:
import kagglehub
import pandas as pd
import numpy as np
import re

In [5]:
# Descargar última versión
path = kagglehub.dataset_download("zynicide/wine-reviews")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\jcarl\.cache\kagglehub\datasets\zynicide\wine-reviews\versions\4

In [6]:
# Leer información
df_wine = pd.read_csv('data/winemag-data-130k-v2.csv')
df_wine.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [7]:
# Seleccionar países
countries = [
    'France',
    'Spain'
]

# Filtrar países
mask = df_wine['country'].isin(countries)
df_wine = df_wine[mask].copy()
df_wine.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
5,5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
7,7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
9,9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
11,11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer
18,18,Spain,"Desiccated blackberry, leather, charred wood a...",Vendimia Seleccionada Finca Valdelayegua Singl...,87,28.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Pradorey 2010 Vendimia Seleccionada Finca Vald...,Tempranillo Blend,Pradorey

In [8]:
# Extraer con regex el año del título
target = 'title'
year = r'(19\d{2}|20\d{2})'
df_wine['year'] = df_wine[target].str.extract(year, expand=False)

df_wine['year'] = pd.to_numeric(
    df_wine['year'],
    errors='coerce'
)

print(df_wine[['title', 'year']].head(10))

                                                title    year
5   Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...  2011.0
7               Trimbach 2012 Gewurztraminer (Alsace)  2012.0
9   Jean-Baptiste Adam 2012 Les Natures Pinot Gris...  2012.0
11            Leon Beyer 2012 Gewurztraminer (Alsace)  2012.0
18  Pradorey 2010 Vendimia Seleccionada Finca Vald...  2010.0
30  Domaine de la Madone 2012 Nouveau  (Beaujolais...  2012.0
42             Henry Fessy 2012 Nouveau  (Beaujolais)  2012.0
49   Vignerons de Bel Air 2011 Eté Indien  (Brouilly)  2011.0
53  Château de Sours 2011 La Fleur d'Amélie  (Bord...  2011.0
63          Roland Champion NV Brut Rosé  (Champagne)     NaN

In [9]:
# Verificar los cambios
df_wine.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,year
5,5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem,2011.0
7,7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach,2012.0
9,9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam,2012.0
11,11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer,2012.0
18,18,Spain,"Desiccated blackberry, leather, charred wood a...",Vendimia Seleccionada Finca Valdelayegua Singl...,87,28.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Pradorey 2010 Vendimia Seleccionada Finca Vald...,Tempranillo Blend,Pradorey,2010.0

In [10]:
# Seleccionar columnas de interés
cols = [
    'country',
    'description',
    'designation',
    'points',
    'price',
    'province',
    'region_1',
    'title',
    'variety',
    'year'
]

df_wine = df_wine[cols]
df_wine.head()

,country,description,designation,points,price,province,region_1,title,variety,year
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,2011.0
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,2012.0
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,2012.0
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,2012.0
18,Spain,"Desiccated blackberry, leather, charred wood a...",Vendimia Seleccionada Finca Valdelayegua Singl...,87,28.0,Northern Spain,Ribera del Duero,Pradorey 2010 Vendimia Seleccionada Finca Vald...,Tempranillo Blend,2010.0

In [11]:
# Eliminar datos nulos
cols=[
    'year',
    'variety',
    'price',
    'region_1',
    'designation'
]

df_wine_clean = df_wine.dropna(subset=cols).copy()
df_wine_clean = df_wine_clean.reset_index(drop=True)

In [12]:
# Eliminar datos por debajo de 2004
mask_year = (df_wine_clean['year'] >= 2004)
df_wine_clean = df_wine_clean[mask_year].copy()

In [13]:
# Verificar cambios
df_wine_clean.head()

,country,description,designation,points,price,province,region_1,title,variety,year
0,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,2011.0
1,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,2012.0
2,Spain,"Desiccated blackberry, leather, charred wood a...",Vendimia Seleccionada Finca Valdelayegua Singl...,87,28.0,Northern Spain,Ribera del Duero,Pradorey 2010 Vendimia Seleccionada Finca Vald...,Tempranillo Blend,2010.0
3,France,"This is a festive wine, with soft, ripe fruit ...",Nouveau,86,9.0,Beaujolais,Beaujolais,Henry Fessy 2012 Nouveau (Beaujolais),Gamay,2012.0
4,France,"Soft and fruity, this is a generous, ripe wine...",Eté Indien,86,14.0,Beaujolais,Brouilly,Vignerons de Bel Air 2011 Eté Indien (Brouilly),Gamay,2011.0

In [14]:
# Calcular porcentaje de nulos
print('Datos nulos:')
null_data = (df_wine_clean.isnull().sum() / len(df_wine_clean)) * 100
print(null_data[null_data > 0].sort_values(ascending=False))

Datos nulos:
Series([], dtype: float64)

In [15]:
# Guardar documento final
save_path = 'data/wine_clean.csv'

df_wine_clean.to_csv(
    save_path,
    sep=';',
    index=False,
    encoding='utf-8-sig'
)

print(f"DataFrame guardado con éxito en: {save_path}")

DataFrame guardado con éxito en: data/wine_clean.csv